### ISSUE TITLE
"SyntaxError: unexpected character after line continuation character"

### ISSUE THREAD

**Issue by PizzaLuigi647** [Plouni/mari0_se_ce_to_ae_level_converter#1]
i am sorry to say this and i may sound dumb but i tried to run the 'CE_to_AE_level_converter" file it gave me thisline:"SyntaxError: unexpected character after line continuation character" very sorry to tell you this.

**Comment by Plouni** [comment]
I'm sorry it didn't work for you. Can you tell me what version of Python you're using? or more details about the error, like at what line it happened?

**Comment by PizzaLuigi647** [comment]
python 3.10 (64-Bit) and i dunno so i checked again  i guess it was at 1 line i guess i am very sorry for this happening:   File "<stdin>", line 1
    C:\Users\andyp\Downloads\mari0_se_ce_to_ae_level_converter-main\mari0_se_ce_to_ae_level_converter-main\Retrush\CE_to_AE_level_converter.py
       ^
SyntaxError: unexpected character after line continuation character

**Comment by Plouni** [comment]
I think I know why you get this error... So it's a bit technical but I'll explain to you, you're probably using Windows and tried to download the file "CE_to_AE_level_converter.py" directly from the browser. By doing so, the file is using the LF line ending but Windows usually requires a line neding of CRLF. I may be wrong though...

Anyway, to fix this error, you can either:
-  fix the Line ending to CRLF yourself
-  clone the Git repository with the following command: `gh repo clone Plouni/mari0_se_ce_to_ae_level_converter` (you'll need to have git installed on your machine for this to work...)

Both solutions may be a bit too technical for you but there's nothing else I can do about it... Moreover, and I should have been clearer about this, the converter is not an automatic "convert level and ready to play", you'll usually need to spend a lot of time debugging levels to make them work in AE because the converter is not perfect.

**Comment by Andypizza647** [comment]
alrighty dude thanks for the epic tips dude!

**Comment by PizzaLuigi647** [comment]
alrighty thanks dude!
